name: Build and Release Streamlit App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies from requirements.txt
      run: |
        pip install -r requirements.txt

    # - name: Install testing and linting tools
    #   run: |
    #     pip install pytest
    #     pip install ruff

    # - name: Lint with Ruff
    #   run: ruff .

    # - name: Run Pytest
    #   run: pytest

    - name: Build Executable
      run: pyinstaller --onefile your_streamlit_app.py

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/your_streamlit_app.exe
        asset_name: your_streamlit_app.exe
        asset_content_type: application/octet-stream
